version: "3.8"

services:
  app1:
    build: .
    container_name: backend-1
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=rinha
      - NATS_URL=nats://nats:4222  # <-- nova variável
    ports:
      - "9001:9999"
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "150MB"
    depends_on:
      - db
      - nats  # <-- depende do NATS
    networks:
      - rinha-net

  app2:
    build: .
    container_name: backend-2
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=rinha
      - NATS_URL=nats://nats:4222  # <-- nova variável
    ports:
      - "9002:9999"
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "150MB"
    depends_on:
      - db
      - nats
    networks:
      - rinha-net

  nginx:
    image: nginx:alpine
    container_name: nginx-lb
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - app1
      - app2
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"
    networks:
      - rinha-net

  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "40MB"
    networks:
      - rinha-net

  nats:
    image: nats:2.10
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222" # Porta para monitoramento (opcional)
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"
    networks:
      - rinha-net

networks:
  rinha-net:
    driver: bridge
