version: "3.8"

services:
  app1:
    build: .
    container_name: backend-1
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=rinha
      # REMOVA/COMENTE a variável REDIS_URL para não usar redis
    ports:
      - "9001:9999"
    deploy:
      resources:
        limits:
          cpus: "0.65"      # metade da CPU disponível para backend-1
          memory: "150MB"   # metade da memória disponível para backend-1
    depends_on:
      - db
    networks:
      - rinha-net

  app2:
    build: .
    container_name: backend-2
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=rinha
      # REMOVA/COMENTE a variável REDIS_URL para não usar redis
    ports:
      - "9002:9999"
    deploy:
      resources:
        limits:
          cpus: "0.65"      # metade da CPU disponível para backend-2
          memory: "150MB"   # metade da memória disponível para backend-2
    depends_on:
      - db
    networks:
      - rinha-net

  nginx:
    image: nginx:alpine
    container_name: nginx-lb
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - app1
      - app2
    deploy:
      resources:
        limits:
          cpus: "0.2"       # reservar pouca cpu para nginx
          memory: "30MB"
    networks:
      - rinha-net

  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "40MB"
    networks:
      - rinha-net

networks:
  rinha-net:
    driver: bridge
